"""initial schema

Revision ID: 9656a21b3757
Revises:
Create Date: 2026-08-31 03:41:13.680470

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9656a21b3757"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tenants", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tenants_slug"), ["slug"], unique=True)

    op.create_table(
        "handbooks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column(
            "handbook_type",
            sa.Enum("VISUAL", "DIRECTOR", name="handbooktype", native_enum=False),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("cover_url", sa.String(length=500), nullable=True),
        sa.Column("skill_path", sa.String(length=300), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "handbook_type", "name", name="uq_handbook_name"),
    )
    with op.batch_alter_table("handbooks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_handbooks_handbook_type"), ["handbook_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_handbooks_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "prompt_templates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "code", name="uq_prompt_template_code"),
    )
    with op.batch_alter_table("prompt_templates", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_prompt_templates_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "providers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "provider_type",
            sa.Enum(
                "SUB2API", "NEW_API", "OPENAI_COMPATIBLE", "CUSTOM", name="providertype", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("base_url", sa.String(length=500), nullable=False),
        sa.Column("encrypted_api_key", sa.Text(), nullable=True),
        sa.Column("extra_headers", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_tested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_test_ok", sa.Boolean(), nullable=True),
        sa.Column("last_test_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "code", name="uq_provider_tenant_code"),
    )
    with op.batch_alter_table("providers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_providers_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=80), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.Enum("ADMIN", "USER", name="userrole", native_enum=False), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "email", name="uq_user_tenant_email"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "ai_models",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("provider_id", sa.String(length=36), nullable=False),
        sa.Column("model_id", sa.String(length=160), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column(
            "model_type",
            sa.Enum("TEXT", "IMAGE", "VIDEO", "TTS", name="modeltype", native_enum=False),
            nullable=False,
        ),
        sa.Column("capabilities", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["provider_id"], ["providers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_id", "model_type", "model_id", name="uq_provider_model_type_id"),
    )
    with op.batch_alter_table("ai_models", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ai_models_model_type"), ["model_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_ai_models_provider_id"), ["provider_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_ai_models_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "credit_accounts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("balance", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "user_id", name="uq_credit_account_user"),
    )
    with op.batch_alter_table("credit_accounts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_credit_accounts_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_credit_accounts_user_id"), ["user_id"], unique=False)

    op.create_table(
        "credit_ledger",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("reason", sa.String(length=120), nullable=False),
        sa.Column("reference_type", sa.String(length=50), nullable=True),
        sa.Column("reference_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("credit_ledger", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_credit_ledger_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_credit_ledger_user_id"), ["user_id"], unique=False)

    op.create_table(
        "refresh_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["replaced_by_id"], ["refresh_sessions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    with op.batch_alter_table("refresh_sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_refresh_sessions_expires_at"), ["expires_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_refresh_sessions_revoked_at"), ["revoked_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_refresh_sessions_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_refresh_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "agent_profiles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column(
            "kind", sa.Enum("SCREENPLAY", "GENERAL", name="agentkind", native_enum=False), nullable=False
        ),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.Column("text_model_id", sa.String(length=36), nullable=True),
        sa.Column("memory_enabled", sa.Boolean(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["text_model_id"],
            ["ai_models.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "kind", "name", name="uq_agent_profile_name"),
    )
    with op.batch_alter_table("agent_profiles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_agent_profiles_kind"), ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_agent_profiles_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("cover_url", sa.String(length=500), nullable=True),
        sa.Column("video_model_id", sa.String(length=36), nullable=True),
        sa.Column("video_resolution", sa.String(length=32), nullable=False),
        sa.Column("aspect_ratio", sa.String(length=16), nullable=False),
        sa.Column("image_model_id", sa.String(length=36), nullable=True),
        sa.Column("image_resolution", sa.String(length=8), nullable=False),
        sa.Column("visual_handbook_id", sa.String(length=36), nullable=True),
        sa.Column("director_handbook_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["director_handbook_id"],
            ["handbooks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["image_model_id"],
            ["ai_models.id"],
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["video_model_id"],
            ["ai_models.id"],
        ),
        sa.ForeignKeyConstraint(
            ["visual_handbook_id"],
            ["handbooks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_projects_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_projects_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "agent_chat_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("agent_profile_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("runtime_manifest", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agent_profile_id"], ["agent_profiles.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agent_chat_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_agent_chat_sessions_agent_profile_id"), ["agent_profile_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_agent_chat_sessions_last_message_at"), ["last_message_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_agent_chat_sessions_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_agent_chat_sessions_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_agent_chat_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "agent_memories",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("namespace", sa.String(length=80), nullable=False),
        sa.Column("memory_key", sa.String(length=160), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("memory_metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "user_id", "project_id", "namespace", "memory_key", name="uq_memory_scope"
        ),
    )
    with op.batch_alter_table("agent_memories", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_agent_memories_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_agent_memories_user_id"), ["user_id"], unique=False)

    op.create_table(
        "ai_tasks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("task_type", sa.String(length=80), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED", "RUNNING", "SUCCEEDED", "FAILED", "CANCELLED", name="taskstatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("model_id", sa.String(length=36), nullable=True),
        sa.Column("cost", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("request_payload", sa.JSON(), nullable=False),
        sa.Column("result_payload", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["ai_models.id"],
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ai_tasks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ai_tasks_task_type"), ["task_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_ai_tasks_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_ai_tasks_user_id"), ["user_id"], unique=False)

    op.create_table(
        "assets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column(
            "scope", sa.Enum("PROJECT", "GLOBAL", name="assetscope", native_enum=False), nullable=False
        ),
        sa.Column(
            "asset_type",
            sa.Enum("CHARACTER", "SCENE", "PROP", "MATERIAL", "AUDIO", name="assettype", native_enum=False),
            nullable=False,
        ),
        sa.Column("parent_asset_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("generation_prompt", sa.Text(), nullable=False),
        sa.Column("media_url", sa.String(length=600), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "EXTRACTED",
                "PROMPT_READY",
                "GENERATING",
                "READY",
                "FAILED",
                name="assetstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("asset_metadata", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["parent_asset_id"], ["assets.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_assets_asset_type"), ["asset_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_assets_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_assets_parent_asset_id"), ["parent_asset_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_assets_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_assets_scope"), ["scope"], unique=False)
        batch_op.create_index(batch_op.f("ix_assets_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_assets_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_assets_user_id"), ["user_id"], unique=False)

    op.create_table(
        "project_files",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "SOURCE",
                "MEMORY",
                "ANALYSIS",
                "SCRIPT",
                "ASSET",
                "STORYBOARD",
                "VIDEO",
                "OTHER",
                name="projectfilekind",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("mime_type", sa.String(length=160), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("storage_path", sa.String(length=600), nullable=True),
        sa.Column("editable", sa.Boolean(), nullable=False),
        sa.Column("file_metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("project_files", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_project_files_kind"), ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_project_files_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_project_files_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_project_files_user_id"), ["user_id"], unique=False)

    op.create_table(
        "agent_chat_messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column(
            "role", sa.Enum("USER", "ASSISTANT", name="agentmessagerole", native_enum=False), nullable=False
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=True),
        sa.Column("finish_reason", sa.String(length=80), nullable=True),
        sa.Column("runtime_events", sa.JSON(), nullable=False),
        sa.Column("runtime_manifest", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["agent_chat_sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agent_chat_messages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_agent_chat_messages_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_agent_chat_messages_session_id"), ["session_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_agent_chat_messages_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_agent_chat_messages_user_id"), ["user_id"], unique=False)

    op.create_table(
        "chapters",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("source_file_id", sa.String(length=36), nullable=False),
        sa.Column(
            "source_mode", sa.Enum("NOVEL", "SCRIPT", name="sourcemode", native_enum=False), nullable=False
        ),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("original_content", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "UNINITIALIZED",
                "ANALYZING",
                "ANALYZED",
                "SCRIPTING",
                "REVIEWING",
                "ASSETS",
                "STORYBOARD",
                "VIDEO",
                "COMPLETED",
                name="chapterstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("active_script_version_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_file_id"], ["project_files.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_file_id", "order_index", name="uq_chapter_source_order"),
    )
    with op.batch_alter_table("chapters", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_chapters_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_chapters_source_file_id"), ["source_file_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_chapters_source_mode"), ["source_mode"], unique=False)
        batch_op.create_index(batch_op.f("ix_chapters_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_chapters_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_chapters_user_id"), ["user_id"], unique=False)

    op.create_table(
        "notifications",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("task_id", sa.String(length=36), nullable=True),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("message", sa.String(length=1000), nullable=False),
        sa.Column("notification_metadata", sa.JSON(), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["ai_tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_notifications_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_notifications_is_read"), ["is_read"], unique=False)
        batch_op.create_index(batch_op.f("ix_notifications_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_notifications_task_id"), ["task_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_notifications_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_notifications_user_id"), ["user_id"], unique=False)

    op.create_table(
        "task_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED", "RUNNING", "SUCCEEDED", "FAILED", "CANCELLED", name="taskstatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=False),
        sa.Column("event_metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["ai_tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("task_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_task_events_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_task_events_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_task_events_task_id"), ["task_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_task_events_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_task_events_user_id"), ["user_id"], unique=False)

    op.create_table(
        "chapter_analyses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("chapter_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["chapter_id"], ["chapters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chapter_id", "version", name="uq_chapter_analysis_version"),
    )
    with op.batch_alter_table("chapter_analyses", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_chapter_analyses_chapter_id"), ["chapter_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_chapter_analyses_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_chapter_analyses_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_chapter_analyses_user_id"), ["user_id"], unique=False)

    op.create_table(
        "script_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("chapter_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("review_notes", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["chapter_id"], ["chapters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chapter_id", "version", name="uq_script_chapter_version"),
    )
    with op.batch_alter_table("script_versions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_script_versions_chapter_id"), ["chapter_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_script_versions_is_active"), ["is_active"], unique=False)
        batch_op.create_index(batch_op.f("ix_script_versions_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_script_versions_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_script_versions_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_script_versions_user_id"), ["user_id"], unique=False)

    with op.batch_alter_table("chapters", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_chapters_active_script_version_id_script_versions",
            "script_versions",
            ["active_script_version_id"],
            ["id"],
            ondelete="SET NULL",
        )

    op.create_table(
        "asset_extractions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("chapter_id", sa.String(length=36), nullable=False),
        sa.Column("script_version_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("invalidated_reason", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["chapter_id"], ["chapters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["script_version_id"], ["script_versions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chapter_id", "version", name="uq_asset_extraction_chapter_version"),
    )
    with op.batch_alter_table("asset_extractions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_asset_extractions_chapter_id"), ["chapter_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_asset_extractions_is_active"), ["is_active"], unique=False)
        batch_op.create_index(batch_op.f("ix_asset_extractions_project_id"), ["project_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_asset_extractions_script_version_id"), ["script_version_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_asset_extractions_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_asset_extractions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "storyboard_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("chapter_id", sa.String(length=36), nullable=False),
        sa.Column("script_version_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("invalidated_reason", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["chapter_id"], ["chapters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["script_version_id"], ["script_versions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chapter_id", "version", name="uq_storyboard_chapter_version"),
    )
    with op.batch_alter_table("storyboard_versions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_storyboard_versions_chapter_id"), ["chapter_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_storyboard_versions_is_active"), ["is_active"], unique=False)
        batch_op.create_index(batch_op.f("ix_storyboard_versions_project_id"), ["project_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_storyboard_versions_script_version_id"), ["script_version_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_storyboard_versions_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_storyboard_versions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "asset_extraction_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("extraction_id", sa.String(length=36), nullable=False),
        sa.Column("asset_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["extraction_id"], ["asset_extractions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("extraction_id", "asset_id", name="uq_asset_extraction_item"),
    )
    with op.batch_alter_table("asset_extraction_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_asset_extraction_items_asset_id"), ["asset_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_asset_extraction_items_extraction_id"), ["extraction_id"], unique=False
        )

    op.create_table(
        "storyboard_shots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("chapter_id", sa.String(length=36), nullable=False),
        sa.Column("storyboard_version_id", sa.String(length=36), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("shot_type", sa.String(length=80), nullable=False),
        sa.Column("duration_seconds", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("scene_description", sa.Text(), nullable=False),
        sa.Column("action_description", sa.Text(), nullable=False),
        sa.Column("dialogue", sa.Text(), nullable=False),
        sa.Column("image_prompt", sa.Text(), nullable=False),
        sa.Column("video_prompt", sa.Text(), nullable=False),
        sa.Column("asset_ids", sa.JSON(), nullable=False),
        sa.Column("reference_image_url", sa.String(length=600), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["chapter_id"], ["chapters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["storyboard_version_id"], ["storyboard_versions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storyboard_version_id", "order_index", name="uq_storyboard_shot_order"),
    )
    with op.batch_alter_table("storyboard_shots", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_storyboard_shots_chapter_id"), ["chapter_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_storyboard_shots_project_id"), ["project_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_storyboard_shots_storyboard_version_id"), ["storyboard_version_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_storyboard_shots_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_storyboard_shots_user_id"), ["user_id"], unique=False)

    op.create_table(
        "video_clips",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("chapter_id", sa.String(length=36), nullable=False),
        sa.Column("storyboard_version_id", sa.String(length=36), nullable=False),
        sa.Column("shot_id", sa.String(length=36), nullable=False),
        sa.Column("model_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "GENERATING",
                "READY",
                "FAILED",
                "CANCELLED",
                name="videoclipstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("media_url", sa.String(length=600), nullable=True),
        sa.Column("provider_job_id", sa.String(length=255), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("invalidated_reason", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["chapter_id"], ["chapters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["ai_models.id"],
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["shot_id"], ["storyboard_shots.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["storyboard_version_id"], ["storyboard_versions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("shot_id", "version", name="uq_video_clip_shot_version"),
    )
    with op.batch_alter_table("video_clips", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_video_clips_chapter_id"), ["chapter_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_video_clips_is_active"), ["is_active"], unique=False)
        batch_op.create_index(batch_op.f("ix_video_clips_model_id"), ["model_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_video_clips_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_video_clips_provider_job_id"), ["provider_job_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_video_clips_shot_id"), ["shot_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_video_clips_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_video_clips_storyboard_version_id"), ["storyboard_version_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_video_clips_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_video_clips_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("video_clips", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_video_clips_user_id"))
        batch_op.drop_index(batch_op.f("ix_video_clips_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_video_clips_storyboard_version_id"))
        batch_op.drop_index(batch_op.f("ix_video_clips_status"))
        batch_op.drop_index(batch_op.f("ix_video_clips_shot_id"))
        batch_op.drop_index(batch_op.f("ix_video_clips_provider_job_id"))
        batch_op.drop_index(batch_op.f("ix_video_clips_project_id"))
        batch_op.drop_index(batch_op.f("ix_video_clips_model_id"))
        batch_op.drop_index(batch_op.f("ix_video_clips_is_active"))
        batch_op.drop_index(batch_op.f("ix_video_clips_chapter_id"))

    op.drop_table("video_clips")
    with op.batch_alter_table("storyboard_shots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_storyboard_shots_user_id"))
        batch_op.drop_index(batch_op.f("ix_storyboard_shots_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_storyboard_shots_storyboard_version_id"))
        batch_op.drop_index(batch_op.f("ix_storyboard_shots_project_id"))
        batch_op.drop_index(batch_op.f("ix_storyboard_shots_chapter_id"))

    op.drop_table("storyboard_shots")
    with op.batch_alter_table("asset_extraction_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_asset_extraction_items_extraction_id"))
        batch_op.drop_index(batch_op.f("ix_asset_extraction_items_asset_id"))

    op.drop_table("asset_extraction_items")
    with op.batch_alter_table("storyboard_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_storyboard_versions_user_id"))
        batch_op.drop_index(batch_op.f("ix_storyboard_versions_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_storyboard_versions_script_version_id"))
        batch_op.drop_index(batch_op.f("ix_storyboard_versions_project_id"))
        batch_op.drop_index(batch_op.f("ix_storyboard_versions_is_active"))
        batch_op.drop_index(batch_op.f("ix_storyboard_versions_chapter_id"))

    op.drop_table("storyboard_versions")
    with op.batch_alter_table("asset_extractions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_asset_extractions_user_id"))
        batch_op.drop_index(batch_op.f("ix_asset_extractions_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_asset_extractions_script_version_id"))
        batch_op.drop_index(batch_op.f("ix_asset_extractions_project_id"))
        batch_op.drop_index(batch_op.f("ix_asset_extractions_is_active"))
        batch_op.drop_index(batch_op.f("ix_asset_extractions_chapter_id"))

    op.drop_table("asset_extractions")
    with op.batch_alter_table("chapters", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_chapters_active_script_version_id_script_versions",
            type_="foreignkey",
        )

    with op.batch_alter_table("script_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_script_versions_user_id"))
        batch_op.drop_index(batch_op.f("ix_script_versions_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_script_versions_status"))
        batch_op.drop_index(batch_op.f("ix_script_versions_project_id"))
        batch_op.drop_index(batch_op.f("ix_script_versions_is_active"))
        batch_op.drop_index(batch_op.f("ix_script_versions_chapter_id"))

    op.drop_table("script_versions")
    with op.batch_alter_table("chapter_analyses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chapter_analyses_user_id"))
        batch_op.drop_index(batch_op.f("ix_chapter_analyses_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_chapter_analyses_project_id"))
        batch_op.drop_index(batch_op.f("ix_chapter_analyses_chapter_id"))

    op.drop_table("chapter_analyses")
    with op.batch_alter_table("task_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_task_events_user_id"))
        batch_op.drop_index(batch_op.f("ix_task_events_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_task_events_task_id"))
        batch_op.drop_index(batch_op.f("ix_task_events_status"))
        batch_op.drop_index(batch_op.f("ix_task_events_created_at"))

    op.drop_table("task_events")
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notifications_user_id"))
        batch_op.drop_index(batch_op.f("ix_notifications_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_notifications_task_id"))
        batch_op.drop_index(batch_op.f("ix_notifications_project_id"))
        batch_op.drop_index(batch_op.f("ix_notifications_is_read"))
        batch_op.drop_index(batch_op.f("ix_notifications_category"))

    op.drop_table("notifications")
    with op.batch_alter_table("chapters", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chapters_user_id"))
        batch_op.drop_index(batch_op.f("ix_chapters_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_chapters_status"))
        batch_op.drop_index(batch_op.f("ix_chapters_source_mode"))
        batch_op.drop_index(batch_op.f("ix_chapters_source_file_id"))
        batch_op.drop_index(batch_op.f("ix_chapters_project_id"))

    op.drop_table("chapters")
    with op.batch_alter_table("agent_chat_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_chat_messages_user_id"))
        batch_op.drop_index(batch_op.f("ix_agent_chat_messages_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_agent_chat_messages_session_id"))
        batch_op.drop_index(batch_op.f("ix_agent_chat_messages_run_id"))

    op.drop_table("agent_chat_messages")
    with op.batch_alter_table("project_files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_files_user_id"))
        batch_op.drop_index(batch_op.f("ix_project_files_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_project_files_project_id"))
        batch_op.drop_index(batch_op.f("ix_project_files_kind"))

    op.drop_table("project_files")
    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_assets_user_id"))
        batch_op.drop_index(batch_op.f("ix_assets_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_assets_status"))
        batch_op.drop_index(batch_op.f("ix_assets_scope"))
        batch_op.drop_index(batch_op.f("ix_assets_project_id"))
        batch_op.drop_index(batch_op.f("ix_assets_parent_asset_id"))
        batch_op.drop_index(batch_op.f("ix_assets_name"))
        batch_op.drop_index(batch_op.f("ix_assets_asset_type"))

    op.drop_table("assets")
    with op.batch_alter_table("ai_tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_tasks_user_id"))
        batch_op.drop_index(batch_op.f("ix_ai_tasks_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_ai_tasks_task_type"))

    op.drop_table("ai_tasks")
    with op.batch_alter_table("agent_memories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_memories_user_id"))
        batch_op.drop_index(batch_op.f("ix_agent_memories_tenant_id"))

    op.drop_table("agent_memories")
    with op.batch_alter_table("agent_chat_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_chat_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_agent_chat_sessions_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_agent_chat_sessions_project_id"))
        batch_op.drop_index(batch_op.f("ix_agent_chat_sessions_last_message_at"))
        batch_op.drop_index(batch_op.f("ix_agent_chat_sessions_agent_profile_id"))

    op.drop_table("agent_chat_sessions")
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_projects_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_projects_owner_id"))

    op.drop_table("projects")
    with op.batch_alter_table("agent_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_profiles_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_agent_profiles_kind"))

    op.drop_table("agent_profiles")
    with op.batch_alter_table("refresh_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_refresh_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_refresh_sessions_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_refresh_sessions_revoked_at"))
        batch_op.drop_index(batch_op.f("ix_refresh_sessions_expires_at"))

    op.drop_table("refresh_sessions")
    with op.batch_alter_table("credit_ledger", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_credit_ledger_user_id"))
        batch_op.drop_index(batch_op.f("ix_credit_ledger_tenant_id"))

    op.drop_table("credit_ledger")
    with op.batch_alter_table("credit_accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_credit_accounts_user_id"))
        batch_op.drop_index(batch_op.f("ix_credit_accounts_tenant_id"))

    op.drop_table("credit_accounts")
    with op.batch_alter_table("ai_models", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_models_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_ai_models_provider_id"))
        batch_op.drop_index(batch_op.f("ix_ai_models_model_type"))

    op.drop_table("ai_models")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("providers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_providers_tenant_id"))

    op.drop_table("providers")
    with op.batch_alter_table("prompt_templates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_prompt_templates_tenant_id"))

    op.drop_table("prompt_templates")
    with op.batch_alter_table("handbooks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_handbooks_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_handbooks_handbook_type"))

    op.drop_table("handbooks")
    with op.batch_alter_table("tenants", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tenants_slug"))

    op.drop_table("tenants")
    # ### end Alembic commands ###
