"""add dialogue dubbing pipeline

Revision ID: 9c067b4c7763
Revises: 9656a21b3757
Create Date: 2026-08-31 04:01:17.379968

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c067b4c7763"
down_revision: str | Sequence[str] | None = "9656a21b3757"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "voice_bindings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("character_asset_id", sa.String(length=36), nullable=False),
        sa.Column("tts_model_id", sa.String(length=36), nullable=False),
        sa.Column("provider_voice_id", sa.String(length=255), nullable=False),
        sa.Column("provider_voice_name", sa.String(length=255), nullable=False),
        sa.Column("style", sa.String(length=255), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["character_asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["tts_model_id"],
            ["ai_models.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "character_asset_id", name="uq_voice_project_character"),
    )
    with op.batch_alter_table("voice_bindings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_voice_bindings_character_asset_id"), ["character_asset_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_voice_bindings_enabled"), ["enabled"], unique=False)
        batch_op.create_index(batch_op.f("ix_voice_bindings_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_voice_bindings_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_voice_bindings_tts_model_id"), ["tts_model_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_voice_bindings_user_id"), ["user_id"], unique=False)

    op.create_table(
        "dialogue_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("chapter_id", sa.String(length=36), nullable=False),
        sa.Column("script_version_id", sa.String(length=36), nullable=False),
        sa.Column("storyboard_version_id", sa.String(length=36), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("runtime_manifest", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("invalidated_reason", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["chapter_id"], ["chapters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["script_version_id"], ["script_versions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["storyboard_version_id"], ["storyboard_versions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chapter_id", "version", name="uq_dialogue_chapter_version"),
    )
    with op.batch_alter_table("dialogue_versions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_dialogue_versions_chapter_id"), ["chapter_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_dialogue_versions_is_active"), ["is_active"], unique=False)
        batch_op.create_index(batch_op.f("ix_dialogue_versions_project_id"), ["project_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_dialogue_versions_script_version_id"), ["script_version_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_dialogue_versions_storyboard_version_id"), ["storyboard_version_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_dialogue_versions_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_dialogue_versions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "dialogue_lines",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("chapter_id", sa.String(length=36), nullable=False),
        sa.Column("dialogue_version_id", sa.String(length=36), nullable=False),
        sa.Column("shot_id", sa.String(length=36), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("speaker", sa.String(length=160), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("emotion", sa.String(length=120), nullable=False),
        sa.Column("direction", sa.Text(), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["chapter_id"], ["chapters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["dialogue_version_id"], ["dialogue_versions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["shot_id"], ["storyboard_shots.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dialogue_version_id", "order_index", name="uq_dialogue_line_order"),
    )
    with op.batch_alter_table("dialogue_lines", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_dialogue_lines_chapter_id"), ["chapter_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_dialogue_lines_dialogue_version_id"), ["dialogue_version_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_dialogue_lines_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_dialogue_lines_shot_id"), ["shot_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_dialogue_lines_source_hash"), ["source_hash"], unique=False)
        batch_op.create_index(batch_op.f("ix_dialogue_lines_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_dialogue_lines_user_id"), ["user_id"], unique=False)

    op.create_table(
        "audio_clips",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("chapter_id", sa.String(length=36), nullable=False),
        sa.Column("dialogue_version_id", sa.String(length=36), nullable=False),
        sa.Column("dialogue_line_id", sa.String(length=36), nullable=False),
        sa.Column("voice_binding_id", sa.String(length=36), nullable=False),
        sa.Column("model_id", sa.String(length=36), nullable=False),
        sa.Column("line_version", sa.Integer(), nullable=False),
        sa.Column("binding_version", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "GENERATING",
                "READY",
                "FAILED",
                "CANCELLED",
                name="audioclipstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("media_url", sa.String(length=600), nullable=True),
        sa.Column("provider_job_id", sa.String(length=255), nullable=True),
        sa.Column("duration_seconds", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("invalidated_reason", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["chapter_id"], ["chapters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["dialogue_line_id"], ["dialogue_lines.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["dialogue_version_id"], ["dialogue_versions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["ai_models.id"],
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["voice_binding_id"], ["voice_bindings.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dialogue_line_id", "version", name="uq_audio_line_version"),
    )
    with op.batch_alter_table("audio_clips", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audio_clips_chapter_id"), ["chapter_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audio_clips_dialogue_line_id"), ["dialogue_line_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audio_clips_dialogue_version_id"), ["dialogue_version_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_audio_clips_is_active"), ["is_active"], unique=False)
        batch_op.create_index(batch_op.f("ix_audio_clips_model_id"), ["model_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audio_clips_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audio_clips_provider_job_id"), ["provider_job_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audio_clips_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_audio_clips_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audio_clips_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audio_clips_voice_binding_id"), ["voice_binding_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audio_clips", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audio_clips_voice_binding_id"))
        batch_op.drop_index(batch_op.f("ix_audio_clips_user_id"))
        batch_op.drop_index(batch_op.f("ix_audio_clips_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_audio_clips_status"))
        batch_op.drop_index(batch_op.f("ix_audio_clips_provider_job_id"))
        batch_op.drop_index(batch_op.f("ix_audio_clips_project_id"))
        batch_op.drop_index(batch_op.f("ix_audio_clips_model_id"))
        batch_op.drop_index(batch_op.f("ix_audio_clips_is_active"))
        batch_op.drop_index(batch_op.f("ix_audio_clips_dialogue_version_id"))
        batch_op.drop_index(batch_op.f("ix_audio_clips_dialogue_line_id"))
        batch_op.drop_index(batch_op.f("ix_audio_clips_chapter_id"))

    op.drop_table("audio_clips")
    with op.batch_alter_table("dialogue_lines", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dialogue_lines_user_id"))
        batch_op.drop_index(batch_op.f("ix_dialogue_lines_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_dialogue_lines_source_hash"))
        batch_op.drop_index(batch_op.f("ix_dialogue_lines_shot_id"))
        batch_op.drop_index(batch_op.f("ix_dialogue_lines_project_id"))
        batch_op.drop_index(batch_op.f("ix_dialogue_lines_dialogue_version_id"))
        batch_op.drop_index(batch_op.f("ix_dialogue_lines_chapter_id"))

    op.drop_table("dialogue_lines")
    with op.batch_alter_table("dialogue_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dialogue_versions_user_id"))
        batch_op.drop_index(batch_op.f("ix_dialogue_versions_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_dialogue_versions_storyboard_version_id"))
        batch_op.drop_index(batch_op.f("ix_dialogue_versions_script_version_id"))
        batch_op.drop_index(batch_op.f("ix_dialogue_versions_project_id"))
        batch_op.drop_index(batch_op.f("ix_dialogue_versions_is_active"))
        batch_op.drop_index(batch_op.f("ix_dialogue_versions_chapter_id"))

    op.drop_table("dialogue_versions")
    with op.batch_alter_table("voice_bindings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_voice_bindings_user_id"))
        batch_op.drop_index(batch_op.f("ix_voice_bindings_tts_model_id"))
        batch_op.drop_index(batch_op.f("ix_voice_bindings_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_voice_bindings_project_id"))
        batch_op.drop_index(batch_op.f("ix_voice_bindings_enabled"))
        batch_op.drop_index(batch_op.f("ix_voice_bindings_character_asset_id"))

    op.drop_table("voice_bindings")
    # ### end Alembic commands ###
